{{- if .Values.manager.workers.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-workers
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    {{- include "wazuh.labels" . | nindent 4 }}
  {{- with .Values.manager.workers.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.manager.workers.service.type }}
  {{- if .Values.manager.workers.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.manager.workers.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 1514
      targetPort: 1514
      protocol: TCP
      name: agents-events
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: worker
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
{{- end }}
